version: '3'
services:
  mongo:
    image: 'mongo:latest'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: subi
      MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
    depends_on:
      - api
      - front
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context: './backend'
    volumes:
      - /app/node_modules
      - ./backend:/app
  front:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
    #ports:
     # - '8080:8080'
